services:
  postgres_db:
    image: postgres:15
    hostname: postgres_db
    container_name: postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: supplements
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: prisma
    ports:
      - '5432:5432'
    networks:
      - prisma-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d supplements"]
      interval: 5s
      timeout: 2s
      retries: 20
    volumes:
      - postgres_data:/var/lib/postgresql/data

  server:
    build: 
      context: ./server  
      dockerfile: Dockerfile
    container_name: nest-server
    restart: unless-stopped
    ports:
      - '8080:8080'
    stdin_open: true
    tty: true  # Keeps the container running for debugging
    depends_on:
      postgres_db:
        condition: service_healthy
    environment:
      DATABASE_URL: ${DATABASE_URL}
    env_file:
      - ./server/.env.development.local
    networks:
      - prisma-network
    command: sh -c "npm run db:deploy && node dist/main.js"

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=${VITE_API_URL}
        - VITE_VERCEL_ENV=${VITE_VERCEL_ENV}
    container_name: react-client
    restart: unless-stopped
    ports:
      - "3000:80"
    networks:
      - prisma-network

networks:
  prisma-network:

volumes:
  postgres_data: